#!/usr/bin/env bash
# Shared helpers for beepaboop hooks.
# Reads the Claude Code hook JSON payload from stdin and emits an enriched
# NotifyRequest JSON on stdout via build_payload.

set -euo pipefail

# Hard dependency: every payload is built with jq. Bail out silently rather
# than erroring on each hook event (permission.sh exiting 0 with no output
# means Claude Code falls back to its native prompt).
if ! command -v jq >/dev/null 2>&1; then
    exit 0
fi

CN_PORT="${BEEPABOOP_PORT:-7891}"
CN_HOST="127.0.0.1"
CN_URL="http://${CN_HOST}:${CN_PORT}"

# Shared secret generated by the app on first launch; the server rejects
# POSTs without it. Empty (file missing = app never launched) is fine — the
# request will just be refused.
CN_TOKEN_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/beepaboop/token"
# Trim any trailing newline so it can't split the X-Beepaboop-Token header.
CN_TOKEN="$(tr -d '\r\n' < "$CN_TOKEN_FILE" 2>/dev/null || true)"

# Capture hook stdin once.
CN_HOOK_RAW="$(cat || true)"

cn_jq() { jq -r "$@" <<<"$CN_HOOK_RAW" 2>/dev/null || echo ""; }

# basename with a fallback so an empty path doesn't render as ".".
cn_basename() { if [[ -n "${1:-}" ]]; then basename "$1"; else echo "file"; fi; }

cn_cwd()        { cn_jq '.cwd // empty'; }
cn_session()    { cn_jq '.session_id // empty'; }
cn_transcript() { cn_jq '.transcript_path // empty'; }
cn_tool_name()  { cn_jq '.tool_name // empty'; }
cn_tool_input() { cn_jq '.tool_input // empty | tostring'; }
cn_message()    { cn_jq '.message // empty'; }
cn_hook_event() { cn_jq '.hook_event_name // empty'; }

cn_repo_name() {
    local cwd="$1"
    [[ -z "$cwd" ]] && { echo ""; return; }
    (cd "$cwd" 2>/dev/null && basename "$(git rev-parse --show-toplevel 2>/dev/null || pwd)") || basename "$cwd"
}

cn_branch() {
    local cwd="$1"
    [[ -z "$cwd" ]] && { echo ""; return; }
    (cd "$cwd" 2>/dev/null && git rev-parse --abbrev-ref HEAD 2>/dev/null) || echo ""
}

# Identify the terminal that hosts this hook.
# Echoes "pid|bundle_id|window_title".
# Bundle ID is detected from env vars first (these survive tmux/screen), then
# falls back to walking up the process tree. PID is best-effort: it can be
# empty under tmux because the shell isn't a process descendant of the
# terminal app — the Swift side will look it up by bundle_id as fallback.
cn_terminal_info() {
    local term_pid="" bundle_id="" window_title=""

    # ── env-var fingerprints (work under tmux/screen) ────────────────────
    if   [[ -n "${GHOSTTY_RESOURCES_DIR:-}${GHOSTTY_BIN_DIR:-}" ]];   then bundle_id="com.mitchellh.ghostty"
    elif [[ -n "${ITERM_PROFILE:-}${ITERM_SESSION_ID:-}" ]] || [[ "${TERM_PROGRAM:-}" == "iTerm.app" ]]; then bundle_id="com.googlecode.iterm2"
    elif [[ "${TERM_PROGRAM:-}" == "Apple_Terminal" ]];               then bundle_id="com.apple.Terminal"
    elif [[ "${TERM_PROGRAM:-}" == "WezTerm" ]];                      then bundle_id="com.github.wez.wezterm"
    elif [[ "${TERM_PROGRAM:-}" == "vscode" ]];                       then bundle_id="com.microsoft.VSCode"
    elif [[ -n "${KITTY_WINDOW_ID:-}" ]] || [[ "${TERM:-}" == *kitty* ]]; then bundle_id="net.kovidgoyal.kitty"
    elif [[ -n "${ALACRITTY_LOG:-}" ]] || [[ -n "${ALACRITTY_SOCKET:-}" ]]; then bundle_id="org.alacritty"
    fi

    # ── process walk (best-effort; useful when not in tmux) ─────────────
    local pid="$PPID"
    while [[ -n "$pid" && "$pid" != "1" ]]; do
        local comm
        comm="$(ps -p "$pid" -o comm= 2>/dev/null | tr -d ' ')"
        case "$comm" in
            *iTerm2*|*iTerm*)    term_pid="$pid"; bundle_id="${bundle_id:-com.googlecode.iterm2}";  break ;;
            *Terminal*)          term_pid="$pid"; bundle_id="${bundle_id:-com.apple.Terminal}";      break ;;
            *Alacritty*)         term_pid="$pid"; bundle_id="${bundle_id:-org.alacritty}";           break ;;
            *kitty*)             term_pid="$pid"; bundle_id="${bundle_id:-net.kovidgoyal.kitty}";    break ;;
            *WezTerm*|*wezterm*) term_pid="$pid"; bundle_id="${bundle_id:-com.github.wez.wezterm}";  break ;;
            *ghostty*|*Ghostty*) term_pid="$pid"; bundle_id="${bundle_id:-com.mitchellh.ghostty}";   break ;;
            *Code*Helper*|*Code*) term_pid="$pid"; bundle_id="${bundle_id:-com.microsoft.VSCode}";   break ;;
        esac
        pid="$(ps -p "$pid" -o ppid= 2>/dev/null | tr -d ' ')"
        [[ -z "$pid" ]] && break
    done

    window_title="${ITERM_SESSION_ID:-}"
    [[ -z "$window_title" && -n "${PWD:-}" ]] && window_title="$(basename "$PWD")"
    printf '%s|%s|%s\n' "${term_pid}" "${bundle_id}" "${window_title}"
}

# Build a NotifyRequest JSON.
# args: id kind title context [extra_jq_assignments]
cn_build_payload() {
    local id="$1" kind="$2" title="$3" context="$4"
    local cwd repo branch sess tool tinfo term_pid term_app term_title
    cwd="$(cn_cwd)"
    repo="$(cn_repo_name "$cwd")"
    branch="$(cn_branch "$cwd")"
    sess="$(cn_session)"
    tool="$(cn_tool_name)"
    tinfo="$(cn_terminal_info)"
    IFS='|' read -r term_pid term_app term_title <<<"$tinfo"

    # tmux identity — the app uses this to focus the exact pane and to find
    # the terminal window hosting it (via the client tty), instead of guessing
    # from window titles. Socket path comes from $TMUX ("path,pid,index");
    # binary path is captured because the app runs with a bare LaunchAgent PATH.
    local tmux_session="" tmux_pane="" tmux_window="" tmux_socket="" tmux_bin=""
    if [[ -n "${TMUX:-}" ]] && command -v tmux >/dev/null 2>&1; then
        tmux_bin="$(command -v tmux)"
        tmux_socket="${TMUX%%,*}"
        tmux_pane="${TMUX_PANE:-}"
        if [[ -n "$tmux_pane" ]]; then
            tmux_session="$(tmux display-message -p -t "$tmux_pane" '#{session_name}' 2>/dev/null || true)"
            tmux_window="$(tmux display-message -p -t "$tmux_pane" '#{window_id}' 2>/dev/null || true)"
        else
            tmux_session="$(tmux display-message -p '#{session_name}' 2>/dev/null || true)"
        fi
    fi

    # IMPORTANT: never use `select(...)` directly inside object construction —
    # an empty stream from one field eliminates the whole object. Use if/then/else
    # so each field always produces a concrete value (string or null), then strip
    # the nulls with `with_entries`.
    jq -nc \
        --arg id "$id" \
        --arg kind "$kind" \
        --arg title "$title" \
        --arg context "$context" \
        --arg repo "$repo" \
        --arg branch "$branch" \
        --arg cwd "$cwd" \
        --arg sess "$sess" \
        --arg tool "$tool" \
        --arg term_pid "$term_pid" \
        --arg term_app "$term_app" \
        --arg term_title "$term_title" \
        --arg tmux_session "$tmux_session" \
        --arg tmux_pane "$tmux_pane" \
        --arg tmux_window "$tmux_window" \
        --arg tmux_socket "$tmux_socket" \
        --arg tmux_bin "$tmux_bin" \
        '
        def opt(s): if (s | length) > 0 then s else null end;
        def optnum(s): if (s | length) > 0 then (s | tonumber? // null) else null end;
        {
            id:    $id,
            kind:  $kind,
            title: $title,
            context:     opt($context),
            repoName:    opt($repo),
            branch:      opt($branch),
            cwd:         opt($cwd),
            sessionId:   opt($sess),
            toolName:    opt($tool),
            terminalPid: optnum($term_pid),
            terminalApp: opt($term_app),
            windowTitle: opt($term_title),
            tmuxSession: opt($tmux_session),
            tmuxPane:    opt($tmux_pane),
            tmuxWindowId: opt($tmux_window),
            tmuxSocket:  opt($tmux_socket),
            tmuxBin:     opt($tmux_bin)
        } | with_entries(select(.value != null))
        '
}

# uuidgen ships on macOS; fall back to a random id if it's somehow absent so a
# missing binary can't abort the hook under set -e.
cn_uuid() {
    if command -v uuidgen >/dev/null 2>&1; then
        uuidgen | tr '[:upper:]' '[:lower:]'
    else
        printf 'cn-%s-%s' "$$" "${RANDOM}${RANDOM}"
    fi
}

cn_trim() {
    local s="$1" max="${2:-180}"
    if [[ ${#s} -gt $max ]]; then
        echo "${s:0:$max}…"
    else
        echo "$s"
    fi
}
